#!/bin/bash

dotfiles="$(dirname "$(readlink -f "$0")")"


has() {
    type "$1" >/dev/null 2>&1
}

log() {
    echo "$0: $@"
}

remove_with_backup() {
    if [[ ! -e "$1" ]]; then
        return
    fi

    name="$1"~
    while [[ -e "$name" ]]; do
        name="$name"~
    done
    mv -iv "$1" "$name"
}

ln_safe() {
    target="$1"
    link="$2"
    mkdir -p "$(dirname "$link")"
    if [[ -L "$link" ]]; then
        # if $link is a symbolic link, replace it
        ln -svnf "$target" "$link"
    else
        # otherwise, make a backup before overwriting
        remove_with_backup "$link"
        ln -svni "$target" "$link"
    fi
}

install_pkg() {
    if has "$1"; then
        return
    fi

    sudo=
    if has sudo; then
        sudo=sudo
    fi

    log Installing package "$1"

    if has apt; then
        "$sudo" apt install -y "$1"
    elif has yum; then
        "$sudo" yum install -y "$1"
    elif has brew; then
        brew install "$1"
    fi
}


setup_zsh() {
    log Configuring ZSH

    if ! has zsh; then
        log You can installing standalone version of ZSH by:
        log 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh-bin/master/install)"'
    fi

    if sudo -l && [[ -x /bin/zsh ]]; then
        log Setting default shell to ZSH
        sudo usermod "$USER" -s /bin/zsh
    fi

    log Linking ZSH config files

    # config files
    ln_safe "$dotfiles/zsh/zshrc" "$HOME/.zshrc"
    ln_safe "$dotfiles/zsh/zshenv" "$HOME/.zshenv"

    # powerlevel10k
    ln_safe "$dotfiles/zsh/p10k.zsh" "$HOME/.p10k.zsh"
}


setup_fish() {
    echo Configuring FISH

    if [[ "$(awk -F':' "/^$USER/ { print \$7 }" /etc/passwd)" != '/bin/fish' ]]; then
        sudo usermod "$USER" -s /bin/fish
    fi

    # oh-my-fish
    # curl -L https://get.oh-my.fish | fish

    # fisher
    curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
}


setup_tmux() {
    log Configuring TMUX

    # oh-my-tmux
    log Installing Oh My TMUX
    ln_safe "$dotfiles/tmux/oh-my-tmux" "$HOME/.tmux"
    ln_safe "$dotfiles/tmux/oh-my-tmux/.tmux.conf" "$HOME/.tmux.conf"
    ln_safe "$dotfiles/tmux/tmux.conf.local" "$HOME/.tmux.conf.local"
}



setup-vimplug() {
    curl -fL --create-dirs \
         -o "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}


setup_vim() {
    log Configuring Vim

    # neovim configurations
    ln_safe "$dotfiles/vim" "$HOME/.config/nvim"

    setup-vimplug

    # compatible with vim
    ln_safe "$dotfiles/vim" "$HOME/.vim"
    ln_safe "$dotfiles/vim/init.vim" "$HOME/.vimrc"
}


setup_gdb() {
    log Configuring GDB

    ln_safe "$dotfiles/gdb" "$HOME/.gdb"
    ln_safe "$dotfiles/gdb/gdbinit" "$HOME/.gdbinit"
    ln_safe "$dotfiles/gdb/lldbinit" "$HOME/.lldbinit"
}


setup_git() {
    log Configuring Git
    ln_safe "$dotfiles/git/gitconfig" "$HOME/.gitconfig"
    ln_safe "$dotfiles/git/template" "$HOME/.git_template"
}

_check_dep() {
    if has "$1"; then
        log "Checking if $1 exists... YES"
        return 0
    else
        log "Checking if $1 exists... NO"
        return 1
    fi
}

check_deps() {
    ok=1
    deps=(tmux zsh nvim git unzip)
    for d in $deps; do
        if ! _check_dep $d; then
            ok=0
        fi
    done
    if [[ $ok == 0 ]]; then
    	exit 1
    fi
}

setup_pam() {
    ln_safe "$dotfiles/pam_environment" "$HOME/.pam_environment"
}

init-submods() {
    yadm submodule update --init
}

add_apt_sources() {
    codename=$(lsb_release --codename --short)

    echo "Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $codename
Components: stable
Architectures: amd64
Signed-By: -----BEGIN PGP PUBLIC KEY BLOCK-----
    .
    mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
    lqqwp028AqyY+PRfVMtSYMbjuQuu5byyKR01BbqYhuS3jtqQmljZ/bJvXqnmiVXh
    38UuLa+z077PxyxQhu5BbqntTPQMfiyqEiU+BKbq2WmANUKQf+1AmZY/IruOXbnq
    L4C1+gJ8vfmXQt99npCaxEjaNRVYfOS8QcixNzHUYnb6emjlANyEVlZzeqo7XKl7
    UrwV5inawTSzWNvtjEjj4nJL8NsLwscpLPQUhTQ+7BbQXAwAmeHCUTQIvvWXqw0N
    cmhh4HgeQscQHYgOJjjDVfoY5MucvglbIgCqfzAHW9jxmRL4qbMZj+b1XoePEtht
    ku4bIQN1X5P07fNWzlgaRL5Z4POXDDZTlIQ/El58j9kp4bnWRCJW0lya+f8ocodo
    vZZ+Doi+fy4D5ZGrL4XEcIQP/Lv5uFyf+kQtl/94VFYVJOleAv8W92KdgDkhTcTD
    G7c0tIkVEKNUq48b3aQ64NOZQW7fVjfoKwEZdOqPE72Pa45jrZzvUFxSpdiNk2tZ
    XYukHjlxxEgBdC/J3cMMNRE1F4NCA3ApfV1Y7/hTeOnmDuDYwr9/obA8t016Yljj
    q5rdkywPf4JF8mXUW5eCN1vAFHxeg9ZWemhBtQmGxXnw9M+z6hWwc6ahmwARAQAB
    tCtEb2NrZXIgUmVsZWFzZSAoQ0UgZGViKSA8ZG9ja2VyQGRvY2tlci5jb20+iQI3
    BBMBCgAhBQJYrefAAhsvBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEI2BgDwO
    v82IsskP/iQZo68flDQmNvn8X5XTd6RRaUH33kXYXquT6NkHJciS7E2gTJmqvMqd
    tI4mNYHCSEYxI5qrcYV5YqX9P6+Ko+vozo4nseUQLPH/ATQ4qL0Zok+1jkag3Lgk
    jonyUf9bwtWxFp05HC3GMHPhhcUSexCxQLQvnFWXD2sWLKivHp2fT8QbRGeZ+d3m
    6fqcd5Fu7pxsqm0EUDK5NL+nPIgYhN+auTrhgzhK1CShfGccM/wfRlei9Utz6p9P
    XRKIlWnXtT4qNGZNTN0tR+NLG/6Bqd8OYBaFAUcue/w1VW6JQ2VGYZHnZu9S8LMc
    FYBa5Ig9PxwGQOgq6RDKDbV+PqTQT5EFMeR1mrjckk4DQJjbxeMZbiNMG5kGECA8
    g383P3elhn03WGbEEa4MNc3Z4+7c236QI3xWJfNPdUbXRaAwhy/6rTSFbzwKB0Jm
    ebwzQfwjQY6f55MiI/RqDCyuPj3r3jyVRkK86pQKBAJwFHyqj9KaKXMZjfVnowLh
    9svIGfNbGHpucATqREvUHuQbNnqkCx8VVhtYkhDb9fEP2xBu5VvHbR+3nfVhMut5
    G34Ct5RS7Jt6LIfFdtcn8CaSas/l1HbiGeRgc70X/9aYx/V/CEJv0lIe8gP6uDoW
    FPIZ7d6vH+Vro6xuWEGiuMaiznap2KhZmpkgfupyFmplh0s6knymuQINBFit2ioB
    EADneL9S9m4vhU3blaRjVUUyJ7b/qTjcSylvCH5XUE6R2k+ckEZjfAMZPLpO+/tF
    M2JIJMD4SifKuS3xck9KtZGCufGmcwiLQRzeHF7vJUKrLD5RTkNi23ydvWZgPjtx
    Q+DTT1Zcn7BrQFY6FgnRoUVIxwtdw1bMY/89rsFgS5wwuMESd3Q2RYgb7EOFOpnu
    w6da7WakWf4IhnF5nsNYGDVaIHzpiqCl+uTbf1epCjrOlIzkZ3Z3Yk5CM/TiFzPk
    z2lLz89cpD8U+NtCsfagWWfjd2U3jDapgH+7nQnCEWpROtzaKHG6lA3pXdix5zG8
    eRc6/0IbUSWvfjKxLLPfNeCS2pCL3IeEI5nothEEYdQH6szpLog79xB9dVnJyKJb
    VfxXnseoYqVrRz2VVbUI5Blwm6B40E3eGVfUQWiux54DspyVMMk41Mx7QJ3iynIa
    1N4ZAqVMAEruyXTRTxc9XW0tYhDMA/1GYvz0EmFpm8LzTHA6sFVtPm/ZlNCX6P1X
    zJwrv7DSQKD6GGlBQUX+OeEJ8tTkkf8QTJSPUdh8P8YxDFS5EOGAvhhpMBYD42kQ
    pqXjEC+XcycTvGI7impgv9PDY1RCC1zkBjKPa120rNhv/hkVk/YhuGoajoHyy4h7
    ZQopdcMtpN2dgmhEegny9JCSwxfQmQ0zK0g7m6SHiKMwjwARAQABiQQ+BBgBCAAJ
    BQJYrdoqAhsCAikJEI2BgDwOv82IwV0gBBkBCAAGBQJYrdoqAAoJEH6gqcPyc/zY
    1WAP/2wJ+R0gE6qsce3rjaIz58PJmc8goKrir5hnElWhPgbq7cYIsW5qiFyLhkdp
    YcMmhD9mRiPpQn6Ya2w3e3B8zfIVKipbMBnke/ytZ9M7qHmDCcjoiSmwEXN3wKYI
    mD9VHONsl/CG1rU9Isw1jtB5g1YxuBA7M/m36XN6x2u+NtNMDB9P56yc4gfsZVES
    KA9v+yY2/l45L8d/WUkUi0YXomn6hyBGI7JrBLq0CX37GEYP6O9rrKipfz73XfO7
    JIGzOKZlljb/D9RX/g7nRbCn+3EtH7xnk+TK/50euEKw8SMUg147sJTcpQmv6UzZ
    cM4JgL0HbHVCojV4C/plELwMddALOFeYQzTif6sMRPf+3DSj8frbInjChC3yOLy0
    6br92KFom17EIj2CAcoeq7UPhi2oouYBwPxh5ytdehJkoo+sN7RIWua6P2WSmon5
    U888cSylXC0+ADFdgLX9K2zrDVYUG1vo8CX0vzxFBaHwN6Px26fhIT1/hYUHQR1z
    VfNDcyQmXqkOnZvvoMfz/Q0s9BhFJ/zU6AgQbIZE/hm1spsfgvtsD1frZfygXJ9f
    irP+MSAI80xHSf91qSRZOj4Pl3ZJNbq4yYxv0b1pkMqeGdjdCYhLU+LZ4wbQmpCk
    SVe2prlLureigXtmZfkqevRz7FrIZiu9ky8wnCAPwC7/zmS18rgP/17bOtL4/iIz
    QhxAAoAMWVrGyJivSkjhSGx1uCojsWfsTAm11P7jsruIL61ZzMUVE2aM3Pmj5G+W
    9AcZ58Em+1WsVnAXdUR//bMmhyr8wL/G1YO1V3JEJTRdxsSxdYa4deGBBY/Adpsw
    24jxhOJR+lsJpqIUeb999+R8euDhRHG9eFO7DRu6weatUJ6suupoDTRWtr/4yGqe
    dKxV3qQhNLSnaAzqW/1nA3iUB4k7kCaKZxhdhDbClf9P37qaRW467BLCVO/coL3y
    Vm50dwdrNtKpMBh3ZpbB1uJvgi9mXtyBOMJ3v8RZeDzFiG8HdCtg9RvIt/AIFoHR
    H3S+U79NT6i0KPzLImDfs8T7RlpyuMc4Ufs8ggyg9v3Ae6cN3eQyxcK3w0cbBwsh
    /nQNfsA6uu+9H7NhbehBMhYnpNZyrHzCmzyXkauwRAqoCbGCNykTRwsur9gS41TQ
    M8ssD1jFheOJf3hODnkKU+HKjvMROl1DK7zdmLdNzA1cvtZH/nCC9KPj1z8QC47S
    xx+dTZSx4ONAhwbS/LN3PoKtn8LPjY9NP9uDWI+TWYquS2U+KHDrBDlsgozDbs/O
    jCxcpDzNmXpWQHEtHU7649OXHP7UeNST1mCUCH5qdank0V1iejF6/CfTFU4MfcrG
    YT90qFF93M3v01BbxP+EIY2/9tiIPbrd
    =0YYh
    -----END PGP PUBLIC KEY BLOCK-----" | sudo tee /etc/apt/sources.list.d/docker.sources
}

install_packages() {
    add_apt_sources

    pkgs=(
        bat
        build-essential
        docker-ce
        fd-find
        fish
        git-delta
        nmap
        pipx
        python3-venv
        ripgrep
    )
    sudo apt install "$pkgs[@]"

    sudo ln -s batcat /usr/bin/local/bat
    sudo ln -s fdfind /usr/bin/local/fd

    curl -fsSL 'https://github.com/jesseduffield/lazygit/releases/download/v0.42.0/lazygit_0.42.0_Linux_x86_64.tar.gz' \
        | sudo tar -C /usr/local/bin -xzvf - lazygit
    curl -fsSL 'https://github.com/jesseduffield/lazydocker/releases/download/v0.23.1/lazydocker_0.23.1_Linux_x86_64.tar.gz' \
        | sudo tar -C /usr/local/bin -xzvf - lazydocker
}

setup_docker() {
    sudo usermod --append --groups docker (whoami)
}

setup_ufw() {
    git clone https://github.com/ageis/ufw-application-profiles /tmp/ufw-application-profiles
    sudo cp -nrv /tmp/ufw-application-profiles/applications.d/* /etc/ufw/applications.d

    echo '

# ---

# BEGIN UFW AND DOCKER
*filter
:ufw-user-forward - [0:0]
:ufw-docker-logging-deny - [0:0]
:DOCKER-USER - [0:0]

# allow traffic within the same bridge
-A DOCKER-USER -m physdev --physdev-is-bridged -j RETURN

# consult ufw forward rules
-A DOCKER-USER -j ufw-user-forward

-A DOCKER-USER -p udp -m udp --sport 53 --dport 1024:65535 -j RETURN

-A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
-A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
-A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.16.0.0/12
-A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
-A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
-A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 172.16.0.0/12

-A ufw-docker-logging-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW DOCKER BLOCK] "
-A ufw-docker-logging-deny -j DROP

COMMIT
# END UFW AND DOCKER' | sudo tee /etc/ufw/after.rules
}

main() {
    install_packages
    setup_ufw
    setup_docker

    chsh -s /usr/bin/fish

    check_deps
    init-submods
    setup-vimplug
    log Voila! Setup Finished!
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    # if this script is being executed, not sourced
    main
fi
