#!/bin/bash -x
set -o errexit
set -o nounset
set -o pipefail
if (( BASH_VERSINFO[0] > 4 || \
      (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 4) ))
then
    shopt -s inherit_errexit
fi
PS4='+${BASH_SOURCE##*/}:${LINENO}> '
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

main() {
    install_packages
    setup_docker
    setup_fish
    setup_ufw
    echo Voila! Setup Finished!
}

install_packages() {
    if is_ubuntu; then
        install_packages_ubuntu
    elif is_macos; then
        install_packages_macos
    fi
    install_packages_common
}

install_packages_ubuntu() {
    echo Installing Packages

    add_apt_sources
    sudo apt update

    pkgs=(
        # docker-ce
        # ubuntu-standard
        bat
        bear
        eza
        fasd
        fd-find
        fish
        fzf
        git
        git-delta
        htop
        httpie
        iftop
        jq
        mypy
        neofetch
        neovim
        nmap
        nushell
        p7zip-full
        pigz
        pixz
        python3-ipython
        python3-poetry
        python3-venv
        ranger
        remake
        ripgrep
        shfmt
        tealdeer
        tig
        unzip
        wezterm
        yadm
        zsh
    )
    # some packages may not be available on all systems
    pkgs_as_regex=$(IFS="|"; echo "${pkgs[*]}")
    readarray -t pkgs_avail < <(apt-cache --generate pkgnames | grep -E "^(${pkgs_as_regex})$")
    # install or update
    sudo apt install -y --ignore-missing "${pkgs_avail[@]}"

    prefix=/usr/local/bin
    sudo mkdir -p $prefix

    if ! has bat && has batcat; then
        sudo ln -sf $(command -v batcat) $prefix/bat
    fi

    install_lazygit
    install_lazydocker
    #install_helix
}

install_lazygit() {
    version=$(get_latest_release_version jesseduffield/lazygit)
    if ! has lazygit || [[ $(lazygit --version) != *$version* ]]; then
        curl -fsSL "https://github.com/jesseduffield/lazygit/releases/download/v${version}/lazygit_${version}_$(get_os)_$(get_arch).tar.gz" \
            | sudo tar -C $prefix -xzf - lazygit
    fi
}

install_lazydocker() {
    version=$(get_latest_release_version jesseduffield/lazydocker)
    if ! has lazydocker || [[ $(lazydocker --version) != *$version* ]]; then
        curl -fsSL "https://github.com/jesseduffield/lazydocker/releases/download/v${version}/lazydocker_${version}_$(get_os)_$(get_arch).tar.gz" \
            | sudo tar -C $prefix -xzf - lazydocker
    fi
}

install_helix() {
    version=$(get_latest_release_version helix-editor/helix)
    if ! has hx || [[ $(hx --version) != *$version* ]]; then
        curl -fsSL "https://github.com/helix-editor/helix/releases/download/${version}/helix-${version}-$(get_arch)_$(to_lower "$(get_os)").tar.xz" \
            | sudo tar -C /opt -xJf -
        sudo ln -sf /opt/helix-${version}-x86_64-linux/hx $prefix/hx
    fi
}

add_apt_sources() {
    distro=$(to_lower $(lsb_release --id --short 2>/dev/null))
    codename=$(lsb_release --codename --short)
    arch=$(get_arch)

    if ! curl -fsSL "https://download.docker.com/linux/$distro/dists/$codename/stable/binary-$arch/" &>/dev/null; then
        # fallback
        distro=debian
        codename=bookworm
    fi

    if semver_le 2.4 $(apt --version | grep -oP '(?<=apt )\d+\.\d+'); then
        sudo perl -i -pe "s#http://archive\.ubuntu\.com/ubuntu#http://tw.archive.ubuntu.com/ubuntu#g; \
            s#http://ports\.ubuntu\.com/ubuntu-ports#https://mirror.twds.com.tw/ubuntu-ports#g" \
            /etc/apt/sources.list.d/ubuntu.sources
        for sources in "${SCRIPT_DIR}"/../apt/*.sources; do
            (
                export distro codename arch
                envsubst < $sources | sudo tee /etc/apt/sources.list.d/${sources##*/} >/dev/null
            )
        done
    else
        sudo perl -i -pe "s#http://archive\.ubuntu\.com/ubuntu#http://tw.archive.ubuntu.com/ubuntu#g; \
            s#http://ports\.ubuntu\.com/ubuntu-ports#https://mirror.twds.com.tw/ubuntu-ports#g" \
            /etc/apt/sources.list
    fi
}

get_latest_release_version() {
    curl -fsSL "https://api.github.com/repos/$1/releases/latest" \
        | perl -ne 'print $1 if /"tag_name":\s*"v?(.*?)"/'
}

install_packages_macos() {
    echo Installing Packages

    pkgs=(
        # docker
        # fasd
        # wezterm
        bat
        bear
        coreutils
        eza
        fd
        fish
        fzf
        git
        git-delta
        helix
        htop
        iftop
        jq
        lazydocker
        lazygit
        neovim
        nmap
        nushell
        poetry
        python3
        ranger
        remake
        ripgrep
        shfmt
        starship
        tealdeer
        unzip
        uv
        yadm
        zoxide
    )
    for pkg in "${pkgs[@]}"; do
        brew install $pkg || true
    done
}

install_packages_common() {
    sh <(curl -fsSL https://astral.sh/uv/install.sh)
    sh <(curl -fsSL https://starship.rs/install.sh) -y
    sh <(curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh)

    pip_pkgs=(
        pre-commit
        ruff
        shell-gpt
    )
    for pkg in "${pip_pkgs[@]}"; do
        "${HOME}/.local/bin/uv" tool install "${pkg}"
    done
}

setup_docker() {
    echo Configuring Docker

    if ! has docker || ! getent group docker >/dev/null; then
        return
    fi

    sudo usermod --append --groups docker $USER
}

setup_fish() {
    echo Configuring Fish Shell

    if is_macos; then
        # Changing shell requires sudo and can modify system files.
        # On macOS, we prefer to do it manually.
        return
    fi

    shell=/usr/bin/fish

    if [[ ! -e $shell ]]; then
        return
    fi

    sudo chsh -s $shell $USER
}

setup_ufw() {
    echo Configuring UFW

    if ! has ufw; then
        return
    fi

    tmpdir=$(mktemp --directory)
    mkdir -p $tmpdir
    git clone https://github.com/ageis/ufw-application-profiles $tmpdir
    sudo cp -nrv $tmpdir/applications.d/* /etc/ufw/applications.d

    echo '

# ---

# BEGIN UFW AND DOCKER
*filter
:ufw-user-forward - [0:0]
:ufw-docker-logging-deny - [0:0]
:DOCKER-USER - [0:0]

# allow traffic within the same bridge
-A DOCKER-USER -m physdev --physdev-is-bridged -j RETURN

# consult ufw forward rules
-A DOCKER-USER -j ufw-user-forward

-A DOCKER-USER -p udp -m udp --sport 53 --dport 1024:65535 -j RETURN

-A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 192.168.0.0/16
-A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 10.0.0.0/8
-A DOCKER-USER -j ufw-docker-logging-deny -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -d 172.16.0.0/12
-A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 192.168.0.0/16
-A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 10.0.0.0/8
-A DOCKER-USER -j ufw-docker-logging-deny -p udp -m udp --dport 0:32767 -d 172.16.0.0/12

-A ufw-docker-logging-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW DOCKER BLOCK] "
-A ufw-docker-logging-deny -j DROP

COMMIT
# END UFW AND DOCKER' | sudo tee -a /etc/ufw/after.rules >/dev/null
}

passwdless_sudo() {
    cat <<EOF | sudo tee /etc/sudoers.d/ubuntu >/dev/null
# User rules for ubuntu
ubuntu ALL=(ALL) NOPASSWD:ALL

# avoid password for sudo -v
Defaults:ubuntu !authenticate
EOF
}


# Utility functions

has() {
    command -v $1 &>/dev/null
}

to_lower() {
    echo ${1,,}
}

is_package_installed_ubuntu() {
    dpkg-query --show --showformat='${Status}' $1 2>/dev/null | grep -q "ok installed"
}

is_ubuntu() {
    [[
        $(get_os) = Linux &&
        (
            $(lsb_release --id --short 2>/dev/null) = Ubuntu ||
            $(lsb_release --id --short 2>/dev/null) = Kali
        )
    ]]
}

is_macos() {
    [[ $(get_os) = Darwin ]]
}

get_os() {
    uname -s
}

get_arch() {
    dpkg --print-architecture
}

# Compare two semantic version strings
semver_cmp() {
    local vers1=$1
    local vers2=$2

    # Split the versions into parts (major, minor, patch)
    IFS='.' read -r -a parts1 <<< "$vers1"
    IFS='.' read -r -a parts2 <<< "$vers2"

    # Compare each part of the semantic version
    for i in {0..2}; do
        # Default missing parts to 0
        local part1=${parts1[i]:-0}
        local part2=${parts2[i]:-0}

        if (( part1 < part2 )); then
            echo -1
            return
        elif (( part1 > part2 )); then
            echo 1
            return
        fi
    done

    # If all parts are equal, return 0
    echo 0
}

semver_lt() {
    (( $(semver_cmp $1 $2) < 0 ))
}

semver_le() {
    (( $(semver_cmp $1 $2) <= 0 ))
}

# Entry point

if [[ ${BASH_SOURCE[0]} = $0 ]]; then
    # if this script is being executed instead of being sourced
    main
fi
