# profiling time usage, prologue
# zmodload zsh/zprof


# check if command exists, return 0 on success
# MUCH faster than external program `which` since this don't
# require forking process
# TODO: type vs. command -v
has() {
    type "$1" >/dev/null 2>&1
}


# Launch tmux at start
if [ -z "$TMUX" ] && [ "$(hostname)" != 'soyccanmac.local' ]; then
    tmux a
fi

################
# Environments #
################
# PATH
# /usr/local/opt/llvm/bin is path of Homebrew
for p in '/snap/bin' \
         '/usr/local/opt/llvm/bin' \
         "$HOME/go/bin" \
         "$HOME/.rvm/bin" \
         "$HOME/.pyenv/bin" \
         "$HOME/bin"; do
    [ -d "$p" ] && PATH="$p:$PATH"
done
export PATH

# pyenv
if has pyenv; then
    export PATH="$(pyenv root)/shims:$PATH"
    pyenv() {
        # lazy load
        unset -f pyenv
        eval "$(command pyenv init -)"
        eval "$(command pyenv virtualenv-init -)"
        pyenv "$@"
    }
fi

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vi'
has vim && export EDITOR='vim'
has nvim && export EDITOR='nvim'


###########
# Plugins #
###########
### Added by Zinit's installer
if [ ! -f $HOME/.zinit/bin/zinit.zsh ]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node
### End of Zinit's installer chunk


source "$HOME/.config/zsh/plugins.zsh"
source "$HOME/.config/zsh/aliases.zsh"


# completion
# TODO: what do these do? these cause about 0.1s delay
# autoload -Uz compinit
# compinit
# zinit cdreplay -q


# profiling time usage, epilogue
# zprof
