#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "tender"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    enable_vimfiler_gitstatus = true

    bootstrap_before = "myspacevim#before"


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#c'

[[layers]]
name = 'format'

[[layers]]
name = 'checkers'
enable_neomake = true
lint_on_the_fly	= true

# language server protocol, conflict with checkers
# [[layers]]
# name = "lsp"

[[layers]]
name = "gtags"
gtagslabel = "gtags"
# gtagslabel = "pygments"

[[layers]]
# bootmarks
name = "tools"

[[layers]]
name = "denite"

[[custom_plugins]]
name = 'jacoborus/tender.vim'
